[project]
name = "classical-quantum-hybridmachinelearning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Quang", email = "usaltybroxd@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "docx>=0.2.4",
    "imblearn>=0.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
    "pandas>=3.0.5",
    "scikit-learn>=1.9.0",
    "seaborn>=0.13.2",
    "torch>=2.14.0",
    "xgboost>=3.4.1",
]

[project.scripts]
classical-quantum-hybridmachinelearning = "classical_quantum_hybridmachinelearning:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
